# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "2.1"

services:

  unit-poet2:
    container_name: poet2-test
    build:
      context: ./
      dockerfile: ./poet2-sgx-engine.dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./:/project/sawtooth-poet2/
    working_dir: '/project/sawtooth-poet2/src/core'
    command:  cargo test
    stop_signal: SIGKILL
