# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f tests/Dockerfile-liveness-installed -t poet-liveness-test .

# -------------=== poet-tests build ===-------------

FROM ubuntu:bionic as sawtooth-poet-tests-builder

RUN apt-get update \
 && apt-get install gnupg -y

ENV VERSION=AUTO_STRICT

RUN echo "deb http://repo.sawtooth.me/ubuntu/ci bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8AA7AF1F1091A5FD) \
 && apt-get update \
 && apt-get install -y -q \
    git \
    python3 \
    python3-grpcio-tools \
    python3-grpcio \
    python3-protobuf \
    python3-stdeb

COPY . /project

RUN /project/bin/protogen \
 && cd /project/tests/ \
 && if [ -d "debian" ]; then rm -rf debian; fi \
 && python3 setup.py clean --all \
 && python3 setup.py --command-packages=stdeb.command debianize \
 && if [ -d "packaging/ubuntu" ]; then cp -R packaging/ubuntu/* debian/; fi \
 && DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b -rfakeroot -us -uc

# -------------=== poet-tests docker build ===-------------

FROM hyperledger/sawtooth-shell:nightly

RUN apt-get update \
 && apt-get install gnupg -y

COPY --from=sawtooth-poet-tests-builder /project/python3-sawtooth-poet-tests*.deb /tmp

RUN echo "deb http://repo.sawtooth.me/ubuntu/nightly bionic universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && apt-get install -y -q python3 python3-yaml \
 && dpkg -i /tmp/python3-sawtooth-*.deb || true \
 && apt-get -f -y install

RUN apt-get update \
 && apt-get install -y \
    curl \
    python3-nose2 \
    python3-pip \
    sawtooth-intkey-workload \
    sawtooth-smallbank-workload

RUN pip3 install coverage --upgrade
