# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# -------------=== validator registry tp deb build ===-------------
FROM ubuntu:xenial as validator-reg-tp-builder

RUN echo "deb [arch=amd64] http://repo.sawtooth.me/ubuntu/ci xenial universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8AA7AF1F1091A5FD \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 8AA7AF1F1091A5FD) \
 && apt-get update \
 && apt-get install -y -q --allow-downgrades \
    build-essential \
    curl \
    cmake \
    libssl-dev \
    gcc \
    git \
    libzmq3-dev \
    openssl \
    pkg-config \
    python3 \
    unzip \
    clang \
    libclang-dev \
    libc6-dev \
    libjson-c-dev \
    libcrypto++-dev \
    make \
    python3-grpcio-tools=1.1.3-1 \
    && apt-get clean \
 && rm -rf /var/lib/apt/lists/*


RUN \
 if [ ! -z $HTTP_PROXY ] && [ -z $http_proxy ]; then \
  http_proxy=$HTTP_PROXY; \
 fi; \
 if [ ! -z $http_proxy ]; then \
  http_proxy_host=$(printf $http_proxy | sed 's|http.*://\(.*\):\(.*\)$|\1|');\
  http_proxy_port=$(printf $http_proxy | sed 's|http.*://\(.*\):\(.*\)$|\2|');\
  mkdir -p $HOME/.cargo \
  && echo "[http]" >> $HOME/.cargo/config \
  && echo 'proxy = "'$http_proxy_host:$http_proxy_port'"' >> $HOME/.cargo/config \
  && cat $HOME/.cargo/config; \
 fi;

# For Building Protobufs
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
 && curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
 && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
 && rm protoc-3.5.1-linux-x86_64.zip

WORKDIR /tmp

ENV PATH=$PATH:/protoc3/bin:/root/.cargo/bin
RUN /root/.cargo/bin/cargo install cargo-deb

COPY . /project/sawtooth-poet

WORKDIR /project/sawtooth-poet/validator-registry-tp

RUN bash -c "/root/.cargo/bin/cargo deb"

# -------------=== validator registry tp docker build ===-------------
FROM ubuntu:xenial

COPY --from=validator-reg-tp-builder /project/sawtooth-poet/validator-registry-tp/target/debian/validator-registry*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/validator-registry*.deb || true \
 && apt-get -f -y install

CMD validator-registry-tp
