# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

  poet-engine:
    image: sawtooth-poet-engine:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  poet-cli:
    image: sawtooth-poet-cli:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  poet-common:
    image: sawtooth-poet-common:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  poet-core:
    image: sawtooth-poet-core:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  poet-validator-registry:
    image: sawtooth-poet-validator-registry-tp:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  poet-sgx:
    image: sawtooth-poet-sgx:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  poet-simulator:
    image: sawtooth-poet-simulator:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "
  ias_client:
    image: sawtooth-ias-client:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  ias_proxy:
    image: sawtooth-ias-proxy:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  poet-tests:
    image: sawtooth-poet-tests:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "
